### ISSUE TITLE
Issue compiling 

### ISSUE THREAD

**Issue by uaktags** [reyandme/kam_remake#137]
Testing on Win10 with Delphi 10.3
git checkout tags/r11740
opening Utils/Rxxpacker/Rxxpacker.dpr, run "Compile RxxPacker" ends with a fatal error:

```
[dcc32 Fatal Error] KM_RandomMapGenerator.pas(2887): F2084 Internal Error: AV0DC53322(0DB40000)-R00000320-0
```
Also, step 6 seems to be out of order. One of the first issues that pop up is the fact that we need the  UserSecureAuth disabled in the .inc file, otherwise it'll fail long before making it to this RandomMapGenerator. Not too sure why its compiling that far though, figured it should only be doing the RxxPacker.

**Comment by reyandme** [comment]
I noticed that too recently. Will look into it later.
Meanwhile you can compile KamRemake project first and only then compile RXXPacker. 
Works for me

**Comment by uaktags** [comment]
Trying to push ahead with step 8 leads to further issues:

```
[dcc32 Fatal Error] KM_FogOfWar.pas(115): F2613 Unit 'KM_ConsoleTimer' not found.
```
Had to add it manually to the KaM_Remake.dproj via drag and drop.

**Comment by reyandme** [comment]
Thx for information.
What is the problem with buttons? Could you make a screenshot?
Also if you have any other questions / ideas etc please dont' hesitate to find me on official KaM Remake discord channel: https://discord.gg/AMjxRr

**Comment by uaktags** [comment]
Sounds good, I'll be in there.
As for the graphical: 
![2020-05-09 19_20_04-KaM Remake - r11740 (UNSECURE!)](https://user-images.githubusercontent.com/893684/81487399-63457700-922a-11ea-9853-33af1b04c016.png)

**Comment by reyandme** [comment]
Good.
As for buttons: try to copy palette files from previous remake versions or from beta version.
They are located in `data\gfx` folder, all of them. Extensions are `.bbm` or `.lbm`
Then run RXXPacker again and repack rxGui and rxGuiMain

**Comment by reyandme** [comment]
Issue is no longer actual

**Comment by AndreiCherniaev** [comment]
@reyandme what I do wrong? I can't compile in XE2
![ KaM_Remake - Delphi XE2 ](https://user-images.githubusercontent.com/27889022/117036312-57de3c00-ad16-11eb-9004-438f6c89ec09.png)
