### ISSUE TITLE
Issues regarding hotkey settings

### ISSUE THREAD

**Issue by sado1** [reyandme/kam_remake#146]
Someone recently reported issues with setting the hotkeys. I am looking at the issue, and I can confirm that:

- when I go into Settings, change a hotkey, then get back, the new hotkey gets saved properly - at least until Remake is restarted
- when I go into the Settings, and back, without any action, the current hotkeys configuration gets reset to defaults - no matter if it's a configuration done by the Remake running last time, or if I try to edit the XML file directly
- starting Remake, then starting a new game, also clears out the setting

Based on all this I have a feeling that the settings are not loaded properly, when the game is started. I'll try to find out what happens there.

**Comment by sado1** [comment]
In KM_ResKeys.pas, the key bindings are reset in constructor of TKMKeyLibrary class, but it does not load the current settings from XML afterwards - so the current settings will be overwritten by the game defaults:
```delphi
constructor TKMKeyLibrary.Create;
var
  KF: TKMKeyFunction;
begin
  inherited;

  ResetKeymap;
(...)
```
I tried to add Load; after ResetKeymap, but I run into an access violation, and I don't know enough Delphi to fix it properly.
```delphi
procedure TKMKeyLibrary.Load;
begin
  gKeySettings.LoadFromXML;
end;
```
I think that it is not allowed for TKMKeyLibrary to access gKeySettings variable directly. Could someone take a look at it please?

Looking at the code, I can confirm that the problem should happen for hotkeys only.

**Comment by reyandme** [comment]
Thank you
I will take a look

**Comment by reyandme** [comment]
FIxed in https://github.com/reyandme/kam_remake/commit/0475114462d8f5418ec5eaf718e35e6b0039fffa
