### ISSUE TITLE
Can't install .msi file using Wine?

### ISSUE THREAD

**Issue by raziqrakee** [reyandme/kam_remake#172]
Hello, I am having an issue here I'm using MacBook Pro M1 Chip. But I can't figure how to install .msi file using wine, can somebody teach me how? because I have the file already but I can't install it. It gives these command:

preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.19 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000

**Comment by sado1** [comment]
Hi, what MSI are you trying to install? Remake does not use an MSI installer.

**Comment by raziqrakee** [comment]
> Hi, what MSI are you trying to install? Remake does not use an MSI installer.

I'm trying to download Enterprise Architect version 12 which my lecturer provided. This is the file name.
<img width="131" alt="Screenshot 2022-11-02 at 8 47 14 PM" src="https://user-images.githubusercontent.com/97151754/199493404-9d6f97e9-3882-42e2-bf7b-5568c3a9a268.png">
es

**Comment by sado1** [comment]
In that case, I am not sure why you are asking here - this project is not related to the software you are trying to install.
