### ISSUE TITLE
cannot clone https://github.com/KP-Wiki/TranslationManager as a submodule dependency because it does not exist

### ISSUE THREAD

**Issue by dpronin** [reyandme/kam_remake#180]
cloning https://github.com/KP-Wiki/TranslationManager fails because it does not exist

what would we do with it?

**Comment by sado1** [comment]
I don't think it's needed to work on the game's code, so you can safely ignore it for the time being.
It's a standalone tool for translators, it is bundled with the game (in beta version it's in Utils directory).

Rey or Krom should be able to answer where is it located right now, and if it's publicly available.

**Comment by dpronin** [comment]
I just suggest that we remove it from submodules, that's it
