### ISSUE TITLE
Delphi XE2 compilation issues

### ISSUE THREAD

**Issue by Kromster80** [reyandme/kam_remake#66]
Errors:

 * Project Options > Compiling > Debug Information = 2 instead of true

 * can't compile  `GetAllPathsInDir(aDir, aSL, nil, aIncludeSubdirs); `

 * can't compile  `Delete(Arr, Index, 1);`

 * missing unit `System.Hash`

 * strange non-compiling syntax `constructor TKMScriptingPreProcessor.Create; begin Create(nil); end;`

Warnings:

 * specific to platform `IncludeTrailingBackslash`

**Comment by reyandme** [comment]
>>Project Options > Compiling > Debug Information = 2 instead of true
Unfortunally if I set it to True I will get warning in Berlin version. 
Generally I try to keep project warning and hint free, as much as possible, so it will be a bit painfull for me to set it to true for back compatibility.

>> missing unit System.Hash
I can add some directive about it, so project will at least compile on XE2

>>strange non-compiling syntax constructor TKMScriptingPreProcessor.Create; begin Create(nil); end;
>>specific to platform IncludeTrailingBackslash
That could be fixed.

>>can't compile GetAllPathsInDir(aDir, aSL, nil, aIncludeSubdirs);
>>an't compile Delete(Arr, Index, 1);
For those issues I need to check what should we do instead on XE2
