### ISSUE TITLE
[dynamic scripting] no event for move order

### ISSUE THREAD

**Issue by lolslayer** [reyandme/kam_remake#78]
Currently there's no event found that is triggered when ordering a troop to move.

In case that this gets implemented, is it also possible to trigger the event when a unit is stuck in combat?

**Comment by reyandme** [comment]
I added event on group move, check wiki.
What is "stuck in combat" ?

**Comment by TehPlayer14** [comment]
@reyandme Probably means that unit is in group that is fighting but unit isn't

**Comment by reyandme** [comment]
@TehPlayer14 ah, okay, he means when melle group is locked in fight and could not be controlled by player. Okay, we could add that event/state

**Comment by reyandme** [comment]
Actions were added, check wiki
