### ISSUE TITLE
Add DedicatedServer instructions by Rolly

### ISSUE THREAD

**Issue by Kromster80** [reyandme/kam_remake#81]
Download the zip directly on to the server
  Code:
wget http://www.kamremake.com/wp-content/plugins/download-monitor/download.php?id=kam_remake_server_r5547.zip&mirror=0

Change the rev number for newer versions

Unzip it
  Code:
unzip  download.php?id=kam_remake_server_r5547.zip

If you don't have unzip, just install it by: sudo apt-get install unzip

Give the rights
  Code:
chmod +x KaM_Remake_Server_x86_64

This is for the 64 bit version

Then run it
  Code:
./KaM_Remake_Server_x86_64

And then it works, strange... alternativly you can remove the zip by
  Code:
rm download.php?id=kam_remake_server_r5547.zip

To tell a full story
Run it:
  Code:
./KaM_Remake_Server_x86_64

Stop it:
  Code:
Ctrl +C

To run it in the background (start server in SSH session):
  Code:
nohup ./KaM_Remake_Server_x86_64 > log.out 2> log.err < /dev/null &

Stop it (nohup):
  Code:
ps aux | grep KaM

Get the ps (process id) in the second column

  Code:
kill xxxxx

// (c) Rolly from Discord

**Comment by reyandme** [comment]
Thanks!

**Comment by Rolly1989** [comment]
Yeat~！

**Comment by reyandme** [comment]
New page added to wiki
https://github.com/reyandme/kam_remake/wiki/Setup-dedicated-server-instructions-(on-Unix)
